services:
    backend:
        build:
            context: https://github.com/status-im/status-go.git#develop
        container_name: status-backend
        ports:
            - 8080:8080
            - 8081:8081
            - 8545:8545
            - 30303:30303
        entrypoint: 'status-backend'
        command: '-address 0.0.0.0:8080'
        volumes:
            - ./backups:/root/.config/Status/backups
            - ./assets:/assets:ro
        networks:
            - status-bridge
        healthcheck:
            test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 30

networks:
    status-bridge:
        name: status-bridge
        driver: bridge
