services:
    backend:
        build:
            context: https://github.com/status-im/status-go.git#develop
        platform: linux/amd64
        container_name: status-backend
        ports:
            - 8080:8080
            - 8545:8545
            - 30303:30303
        entrypoint: 'status-backend'
        command: '-address 0.0.0.0:8080'
        volumes:
            - ./backups:/root/.config/Status/backups
            - ./assets:/assets:ro
        networks:
            - status-bridge
        healthcheck:
            test: ["CMD", "curl http://0.0.0.0:8080/health"]

networks:
    status-bridge:
        name: status-bridge
        driver: bridge
