services:
    backend:
        build:
            context: https://github.com/status-im/status-go.git#${STATUS_GO_REF:-develop}
        platform: linux/amd64
        container_name: status-backend
        ports:
            - 8080:8080 # backend_port
            - 9000:9000 # media_port
            - 8545:8545
            - 30303:30303
        environment:
            STATUS_GO_MEDIA_SERVER_PORT: "9000"
            STATUS_GO_MEDIA_SERVER_HOST: "0.0.0.0"
        entrypoint: 'status-backend'
        command: '-address 0.0.0.0:8080'
        volumes:
            - ./backups:/root/.config/Status/backups
            - ./assets:/assets:ro
        networks:
            - status-bridge
        healthcheck:
            test: ["CMD", "curl http://0.0.0.0:8080/health"]

networks:
    status-bridge:
        name: status-bridge
        driver: bridge
